import { PieceRegistry, PieceSetName, PieceTheme, PieceCode } from './pieces.types';

// Static mapping generated by scripts/gen-pieces.cjs
let GENERATED: PieceRegistry = {};
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  GENERATED = require('./pieces.generated').PIECES_GENERATED as PieceRegistry;
} catch {}

export const PIECES: PieceRegistry = GENERATED;

export function resolvePiece(set: PieceSetName, theme: PieceTheme, code: PieceCode): any | undefined {
  return (PIECES as any)[set]?.[theme]?.[code];
}


